[theme]

# Primary accent for interactive elements
primaryColor = '#45A29E'

# Background color for the main content area
backgroundColor = '#0B0C10'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#1F2833'

# Color used for almost all text
textColor = '#66FCF1'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
